accessControl:
  enabled: false
api:
  key: 691D9D0B9D6546C5BB0018AEE511032B
appearance: {}
feature: {}
gcodeViewer: {}
plugins:
  cura:
    cura_engine: /usr/share/cura/CuraEngine
  discovery:
    upnpUuid: 9123a423-7f00-4178-93c3-38abe48f87b6
  m3dfio:
    BackLeftOffset: 0.126589
    BackLeftOrientation: 0.079101
    BackRightOffset: 0.200322
    BackRightOrientation: 0.036939
    BacklashSpeed: 15
    BacklashX: 0
    BacklashY: 0.5
    BedHeightOffset: -0.4
    FilamentTemperature: 200
    FrontLeftOffset: 0.231556
    FrontLeftOrientation: -0.296289
    FrontRightOffset: 0.185497
    FrontRightOrientation: -0.399371
    PrinterColor: Blue
    UseCenterModelPreprocessor: true
  pluginmanager:
    pip: /usr/bin/pip
  softwareupdate:
    _config_version: 4
    checks:
      octoprint:
        checkout_folder: /home/john/OctoPrint
printerParameters: {}
printerProfiles:
  default: micro_3d
  defaultProfile: {}
serial:
  timeout: {}
server:
  commands: {}
  firstRun: false
  secretKey: fjiyNRYfEAWGJXH9ZiCOYwQjxyr8CYYw
slicing:
  defaultProfiles:
    cura: test_m3d_pla_0.25mm
system: {}
temperature: {}
webcam: {}
