accessControl:
  enabled: false
api:
  key: 691D9D0B9D6546C5BB0018AEE511032B
appearance: {}
feature: {}
gcodeViewer: {}
plugins:
  cura:
    cura_engine: /usr/share/cura/CuraEngine
  discovery:
    upnpUuid: 9123a423-7f00-4178-93c3-38abe48f87b6
  m3dfio:
    BackLeftOffset: 0.126589
    BackLeftOrientation: -0.033845
    BackRightOffset: 0.200322
    BackRightOrientation: -0.089738
    BacklashSpeed: 15
    BacklashX: 0.75
    BacklashY: 0.73
    BedHeightOffset: -0.4
    FilamentTemperature: 200
    FrontLeftOffset: 0.231556
    FrontLeftOrientation: -0.468608
    FrontRightOffset: 0.185497
    FrontRightOrientation: -0.556024
    PrinterColor: Blue
    UseCenterModelPreprocessor: true
  softwareupdate:
    _config_version: 4
    checks:
      octoprint: {}
printerParameters: {}
printerProfiles:
  default: micro_3d
  defaultProfile: {}
serial:
  timeout: {}
server:
  commands: {}
  firstRun: false
  secretKey: fjiyNRYfEAWGJXH9ZiCOYwQjxyr8CYYw
slicing:
  defaultProfiles:
    cura: m3d_pla_0.2mm
system: {}
temperature: {}
webcam: {}
